#!/usr/bin/env python3
"""
Quick test script for Cognitive Workspace Database with LLM integration.

Run this to verify:
1. Ollama connection works
2. Neo4j connection works
3. LLM text generation works
4. All four cognitive primitives work
"""

from src.server import CognitiveWorkspace, CWDConfig


def main():
    print("🧠 Cognitive Workspace Database - Integration Test\n")
    print("=" * 60)

    # Initialize
    print("\n1️⃣  Initializing workspace...")
    try:
        config = CWDConfig()  # type: ignore[call-arg]
        workspace = CognitiveWorkspace(config)
        print("   ✅ Workspace initialized")
        print(f"   📊 Neo4j: {config.neo4j_uri}")
        print(f"   🤖 LLM: {config.llm_model}")
        print(f"   📁 Chroma: {config.chroma_path}")
    except Exception as e:
        print(f"   ❌ Failed: {e}")
        return

    # Test 1: Deconstruct
    print("\n2️⃣  Testing DECONSTRUCT (breaks problem into components)...")
    try:
        problem = "How can I build an autonomous AI assistant to aid the disabled in daily activities?"
        result = workspace.deconstruct(problem)

        print(f"   ✅ Created {len(result['component_ids'])} thought-nodes")
        print(f"   🌱 Root ID: {result['root_id']}")

        # Show the decomposition tree
        tree = result.get('tree', {})
        if tree and 'children' in tree:
            print("\n   📋 Components generated by LLM:")
            for i, child in enumerate(tree['children'], 1):
                content = child['content']
                print(f"      {i}. {content}")

        # Save IDs for next tests
        component_ids = result['component_ids']

    except Exception as e:
        print(f"   ❌ Failed: {e}")
        workspace.close()
        return

    # Test 2: Hypothesize
    print("\n3️⃣  Testing HYPOTHESIZE (finds connections between concepts)...")
    try:
        if len(component_ids) >= 2:
            hyp = workspace.hypothesize(
                component_ids[0],
                component_ids[1],
                context="Exploring synergies in AI-driven assistance for daily living"
            )

            print("   ✅ Hypothesis generated")
            print(f"   🔗 Similarity score: {hyp['similarity']:.3f}")
            print(f"   💡 Connection:\n{hyp['hypothesis']}")
        else:
            print("   ⚠️  Skipped (need at least 2 components)")
    except Exception as e:
        print(f"   ❌ Failed: {e}")

    # Test 3: Synthesize
    print("\n4️⃣  Testing SYNTHESIZE (merges concepts into unified insight)...")
    synthesis_id = None  # Initialize to avoid unbound variable
    try:
        if len(component_ids) >= 3:
            synth = workspace.synthesize(
                component_ids[:3],
                goal="Integrated approach to AI assistant for the disabled"
            )

            print("   ✅ Synthesis created")
            print(f"   🎯 Unified from {synth['source_count']} nodes")
            print(f"   🌟 Insight:\n{synth['synthesis']}")
            synthesis_id = synth['synthesis_id']
        else:
            print("   ⚠️  Skipped (need at least 3 components)")
    except Exception as e:
        print(f"   ❌ Failed: {e}")

    # Test 4: Constrain
    print("\n5️⃣  Testing CONSTRAIN (validates thought against rules)...")
    try:
        # Pick a node to constrain (use synthesis if available, else first component)
        target_id = synthesis_id if synthesis_id else component_ids[0]

        rules = [
            "Must be technically feasible with current technology",
            "Should be usable as an adjunct to current assistive devices",
            "Must be economically viable"
        ]

        constraint_result = workspace.constrain(target_id, rules)

        print("   ✅ Constraints applied")
        print(f"   📊 Overall score: {constraint_result['overall_score']:.3f}")
        print(f"   {'✅' if constraint_result['all_satisfied'] else '⚠️ '} All rules satisfied: {constraint_result['all_satisfied']}")

        print("\n   📋 Rule validation:")
        for i, rule_result in enumerate(constraint_result['rule_results'], 1):
            satisfied = "✅" if rule_result['satisfied'] else "❌"
            score = rule_result['score']
            rule = rule_result['rule']
            print(f"      {satisfied} [{score:.2f}] {rule}")

    except Exception as e:
        print(f"   ❌ Failed: {e}")

    # Cleanup
    print("\n6️⃣  Cleaning up...")
    workspace.close()
    print("   ✅ Connections closed")

    print("\n" + "=" * 60)
    print("🎉 All tests completed successfully!")
    print("\nYour cognitive workspace is ready for System 2 reasoning!")
    print("\nNext steps:")
    print("  • Explore the graph in Neo4j Browser: http://localhost:7474")
    print("  • Try different LLM models: config.llm_model='mistral:7b'")
    print("  • Add this as an MCP server to Claude Desktop")
    print("=" * 60 + "\n")

if __name__ == "__main__":
    main()
